### ISSUE TITLE
Create field component

### ISSUE THREAD

**Issue by nicolechung** [CrowdStrike/ember-toucan-core#10]
Create a field component.

This will be mostly styling. 

Field is kind of a form-element wrapper exposing label, errors, etc but is not opinionated on the "control" it renders (e.g., an input vs textarea vs select)

Rough API:
```hbs
<!-- Custom input component -->
<form.field as |field|>
    <ToucanCoreField @name="lastName" @label="Last Name">
        <:control>
            <form.controls.Input
                {{on 'change' this.doWhatever}} 
                required 
            />
        </:control>
    </ToucanCoreField>
</form.field>
```

**Comment by ynotdraw** [comment]
Thinking out loud:

I'm kind of thinking we build out _only_ the primitive controls + Field at this point.  Essentially worry about the **presentational** pieces at the moment and "ignore" the `<Form` API for the time being.  I feel like Toucan Core should focus on providing presentational building blocks to consumers, and it's up to them to build the lego of their dreams using our blocks.  By providing only the presentational pieces and allowing consumers to wire things up, it opens the door a bit as to how they can integrate their favorite packages.

We may use `ember-headless-form` for example, but someone else may want to use some other form library or even write their own!  Instead of tying our components to a single form solution, I think pushing it to consumers makes for better composition and separation of concerns (e.g., presentational vs presentation+functional).

---

To support above, here's what we could maybe do.  I'm not sure about file paths / component naming, I also took this from I think either you @NullVoxPopuli or someone else wrote up:

```
<Field @name="..">  
 <:label></:label>
 <:hint></:hint>  
 <:control></:control>  
 <:inlayButtons></:inlayButtons>
 <:error></:error>  
</Field>  
```

Field is essentially a layout component.  It yields back named blocks to put content in particular sections.   The field implementation may be something like ( _super rough_ idea - can land on something better if this seems like a path we want to take ):

```html
// src/components/field.hbs

<div ...attributes>
  <label class="classes">{{yield to="label"}}</label>
  <p class="classes" aria-describedby="">{{yield to="hint"}}</p>
  <div class="classes relative">
    {{yield to="control"}}
    <div class="classes absolute right-0 inset-y-0">{{yield to="inlayButtons"}}</div>
  </div>
  <p class="classes" aria-describedby="">{{yield to="error"}}</p>
</div>
````

From a top-down level, this matches how most folks layer forms structurally:

```
<form label>
<some help text>
<the control>
<error messages (sometimes help text is down here too!>
```

---

We could also provide raw primitives to consumers as well, if they _don't_ want to use our Input+Field component.  This may be unneeded abstraction layering and not really provide much though, I'm not sure:


```html
// src/components/form-components/input.hbs

<input classes="toucan-classes-to-style-our-input" ...attributes />
```

---

**Another thought**

We could provide a Toucan-opinionated Input element that renders a Toucan styled `<input`, but is wrapped in our `<Field` component.  This maybe goes a _bit_ against what I was saying above about building blocks though, as it's combining two concepts - an input control + a presentational layout component for the control.  Instead of forcing the consumer to wire up field + input, we _could_ provide one with a limited API. (Also super rough idea, not fully fleshed out component API, if this seems reasonable let's chat about what this _could_ look like)

```html
// src/components/form-controls/input.hbs

<Field>
  <:label>
    <span>{{@label}}</span>
    <span>{{yield to="supplementalAreaIdk"}}</span>
  </:label>
  <:hint>{{@helperText}}</:hint>
  <:control>
    <input class="toucan-classes-for-inputs" required {{on 'change' this.doWhatever}} ...attributes />
  </:control>
  <:error>
    {{@errors}}
  </:error>
</Field>
```

And then usage:

```hbs
<Input @label="First Name" @helperText="What should we call you?" @errors={{this.errors}} {{on "blur" this.handleBlur}}>
  <:supplementalAreaIdk>(Optional)</:supplementalAreaIdk>
</Input>

This also maybe locks consumers too much, as it doesn't provide as much composition.  Uf they wanted to adjust the label for example, it'd be a bit of a pain as they only have access to `@label`.  `...attributes` should allow them to add modifiers and what not to the control elements, but what if they want to change, say, more than _just_ the help label text?  I'm a bit conflicted.

---

I may have some more thoughts later this evening as I think about it a bit more, but those are kind of my high level immediate thoughts on how we could approach some of these

**Comment by ynotdraw** [comment]
I played around a bit with above, but I'm hitting an issue outlined at https://github.com/CrowdStrike/ember-toucan-core/compare/10-field-prototype-a#diff-6b74531eede9b2af7db5be79e6cc466ce08e9f1c7c604348a819b3a0825f8d76R27.

If we want to expose a `form.Input`-like-control, that'd be a combination of using `<Field` + some sort of input (whether that be `<Input` or `<input`). 

The downside to named-blocks for `<Field` is we can't conditionally render them like:

```hbs
{{#if @helperText}}
  <:hint>{{@helperText}}</:hint>
{{/if}}
```

or

```hbs
{{#if @error}}
  <:error>
    {{@error}}
  </:error>
{{/if}}
```

So our input that includes the label + (optional) help text + (optional) error text renders content into the DOM whether we want it to or not.

<img width="240" alt="Screenshot 2023-02-08 at 10 58 37 AM" src="https://user-images.githubusercontent.com/8069555/217584957-9340995b-128c-413e-90c8-3a5ffe80875d.png">


So for https://github.com/CrowdStrike/ember-toucan-core/compare/10-field-prototype-a#diff-57b54c2a2a424ec4f48f96b2796f279e9714772128807a357fc0a1f67c013e69R100 where we are doing:

```hbs
<InputField @label="Using @label" data-input-field required />
```

We still render the `:hint:` + `:error` divs in the DOM 😭.


<img width="1470" alt="Screenshot 2023-02-08 at 11 09 19 AM" src="https://user-images.githubusercontent.com/8069555/217585745-e79578a3-0419-4f4d-a04b-06f4fe1bf582.png">


---

Due to this, I'm thinking maybe the `<Field` should be a contextual-component to expose these slots?

```hbs
<Field as |field|>
  <field.Label />

  {{#if @helperText}}
    <field.hint />
  {{/if}}

 ... rest
</Field>
```

Or has something changed recently where we _can_ support conditional named blocks?

**Comment by NullVoxPopuli** [comment]
> we can support conditional named blocks?

we cannot, still. though, @wycats brought this up recently in the Ember Discord about unifying how args/blocks/attributes/etc are represented to make all this easier... so the core teams _are_ thinking about it -- but there is just a lot of work to get through (especially design work).

> I'm thinking maybe the <Field should be a contextual-component (via yield + hash to expose these slots?

is it possible for us to still control the layout of a Field? (the focus of slots/blocks in this component)

> We still render the :hint: + :error divs in the DOM 😭.

can the field not have:
```hbs
{{#if (field.hasError)}}
   {{#if (has-block "error")}}
     <div etc>
       {{yield to="error"
     </div>
    {{/if}}
{{/if}}  
```
the headless-form implementation gives us `hasError`, which we can use to wrap around around markup and block yielding. (though, we don't currently have that util added: https://github.com/CrowdStrike/ember-headless-form/blob/main/packages/ember-headless-form/src/components/-private/field.hbs#L50 )

I don't know if we want consumers of the _Toucan_ field to be able to control when/how an error is shown. We can expose headless-form things to help control when errors are added to the errors structure, but the headless-form should be the source of truth for what we render.

We may need to _just test it out_, and we have https://github.com/CrowdStrike/ember-headless-form/pull/34 pending for starting the beta releases
